from django.urls import path
from . import views

app_name = 'patient_roshan'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('book/', views.book_appointment, name='book_appointment'),
    path('find-doctor/', views.find_doctor, name='find_doctor'),
    path('appointments/', views.my_appointments, name='my_appointments'),
    path('appointments/<int:appointment_id>/', views.appointment_detail, name='appointment_detail'),
    path('appointments/<int:appointment_id>/cancel/', views.cancel_appointment, name='cancel_appointment'),
    path('appointments/<int:appointment_id>/reschedule/', views.reschedule_appointment, name='reschedule_appointment'),
    path('records/', views.medical_records, name='medical_records'),
    path('invoices/', views.invoices, name='invoices'),
    path('invoices/<int:invoice_id>/', views.invoice_detail, name='invoice_detail'),
    path('profile/', views.profile, name='profile'),
    path('profile/emergency-contact/', views.update_emergency_contact, name='update_emergency_contact'),
    path('profile/change-password/', views.change_password, name='change_password'),
path('prescriptions/', views.prescriptions, name='prescriptions'),
path('billing/', views.billing, name='billing'),
path('notifications/', views.notifications, name='notifications'),
path('notifications/mark-all-read/', views.mark_all_read, name='mark_all_read'),
path('settings/', views.settings, name='settings'),
    path('settings/notifications/', views.save_notification_preferences, name='save_notification_preferences'),
path('settings/language/', views.save_language, name='save_language'),
path('settings/privacy/', views.save_privacy, name='save_privacy'),
path('settings/deactivate/', views.deactivate_account, name='deactivate_account'),
path('settings/request-deletion/', views.request_deletion, name='request_deletion'),
    path('settings/delete-account/', views.delete_account, name='delete_account'),
    path('get-time-slots/', views.get_time_slots, name='get_time_slots'),
    path('medicine-reminders/', views.medicine_reminders, name='medicine_reminders'),
    path('medicine-reminders/<int:reminder_id>/taken/', views.mark_medicine_taken, name='mark_medicine_taken'),
    path('billing/<int:invoice_id>/pay-counter/', views.pay_at_counter, name='pay_at_counter'),
path('billing/<int:invoice_id>/pay-online/', views.pay_online, name='pay_online'),
path('billing/<int:invoice_id>/esewa/', views.esewa_initiate, name='esewa_initiate'),
path('billing/esewa/verify/', views.esewa_verify, name='esewa_verify'),
path('billing/esewa/failed/', views.esewa_failed, name='esewa_failed'),
path('billing/<int:invoice_id>/khalti/', views.khalti_initiate, name='khalti_initiate'),
path('billing/khalti/verify/', views.khalti_verify, name='khalti_verify'),
path('billing/<int:invoice_id>/receipt/', views.invoice_receipt, name='invoice_receipt'),
]