# Generated by Django 6.0.5 on 2026-08-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_siddhartha', '0002_doctorprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
