# Generated by Django 6.0.5 on 2026-08-19 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_nishan', '0006_populate_invoice_totals'),
        ('doctor_siddhartha', '0003_add_doctor_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('specialization', models.CharField(blank=True, max_length=120)),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('experience_years', models.PositiveSmallIntegerField(default=0)),
                ('license_number', models.CharField(blank=True, max_length=60)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_applications', to='admin_nishan.department')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
