# Generated by Django 6.0.6 on 2026-07-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_roshan', '0002_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='appointment_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='lab_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='language',
            field=models.CharField(default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='profile_visibility',
            field=models.CharField(default='doctors', max_length=20),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='share_records',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='sms_reminders',
            field=models.BooleanField(default=True),
        ),
    ]
