# Generated by Django 6.0.6 on 2026-07-20 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_roshan', '0003_patientprofile_appointment_alerts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
