# Generated by Django 6.0.5 on 2026-08-16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_nishan', '0002_add_medicine_reminder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='labreport',
            old_name='ordered_on',
            new_name='ordered_date',
        ),
        migrations.RemoveField(
            model_name='labreport',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='labreport',
            name='report_url',
        ),
        migrations.AddField(
            model_name='labreport',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='lab_reports/'),
        ),
    ]