# Generated by Django 6.0.7 on 2026-08-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_nishan', '0003_labreport_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labreport',
            options={'ordering': ['-ordered_date', '-created_at']},
        ),
        migrations.AlterField(
            model_name='labreport',
            name='lab_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='labreport',
            name='test_name',
            field=models.CharField(max_length=200),
        ),
    ]
