# Generated by Django 6.0.7 on 2026-08-17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_nishan', '0003_labreport_update'),
        ('patient_roshan', '0004_patientprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labreport',
            options={'ordering': ['-ordered_date', '-created_at']},
        ),
        migrations.AlterField(
            model_name='labreport',
            name='lab_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='labreport',
            name='test_name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Due', 'Due'), ('Paid', 'Paid')], default='Due', max_length=10)),
                ('payment_method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Credit', 'Credit')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_roshan.patientprofile')),
            ],
        ),
    ]