# Generated by Django 6.0.7 on 2026-08-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_nishan', '0004_alter_labreport_options_alter_labreport_lab_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Credit', 'Credit'), ('eSewa', 'eSewa'), ('Khalti', 'Khalti')], max_length=20, null=True),
        ),
    ]
