# Generated by Django 6.0.5 on 2026-08-18 06:15

from django.db import migrations


def populate_invoice_totals(apps, schema_editor):
    BillingInvoice = apps.get_model('admin_nishan', 'BillingInvoice')
    for invoice in BillingInvoice.objects.all():
        invoice.subtotal = invoice.amount
        invoice.tax_amount = 0
        invoice.tax_rate = 0.13
        invoice.grand_total = invoice.amount
        invoice.save(update_fields=['subtotal', 'tax_amount', 'tax_rate', 'grand_total'])


class Migration(migrations.Migration):

    dependencies = [
        ('admin_nishan', '0005_billinginvoice_grand_total_billinginvoice_subtotal_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_invoice_totals, migrations.RunPython.noop),
    ]
